<a href="https://colab.research.google.com/github/nithin790/sql-python-tableau/blob/main/machine_learning_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data_preprocessed =pd.read_csv('/content/df_preprocessed.csv')

In [ ]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                 30          0         2     1                          4  
1                 31          0         1     0                          0  
2                 31          0         0     0                          2  
3                 24          0         2     0                          4  
4                 30          0         2     1                          2  
..               ...        ...       ...   ...                        ...  
695               22          1         2     0                          8  
696               24          0         1     2                          3  
697               25          1         0     0                          8  
698               25          1         0     0                          2  
699               25          0         1     1                          2  

[700 rows x 15 columns]

#Create the traget

In [ ]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [ ]:
data_preprocessed.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Reason_1                   700 non-null    int64  
 1   Reason_2                   700 non-null    int64  
 2   Reason_3                   700 non-null    int64  
 3   Reason_4                   700 non-null    int64  
 4   Month Value                700 non-null    int64  
 5   Day of the Week            700 non-null    int64  
 6   Transportation Expense     700 non-null    int64  
 7   Distance to Work           700 non-null    int64  
 8   Age                        700 non-null    int64  
 9   Daily Work Load Average    700 non-null    float64
 10  Body Mass Index            700 non-null    int64  
 11  Education                  700 non-null    int64  
 12  Children                   700 non-null    int64  
 13  Pets                       700 non-null    int64  

In [ ]:
targets=np.where(data_preprocessed['Absenteeism Time in Hours']>3,4,0)

In [ ]:
targets

array([4, 0, 0, 4, 0, 0, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 0, 4, 4, 0, 4, 0,
       4, 4, 4, 4, 0, 4, 4, 0, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 0, 4, 4, 4,
       0, 0, 0, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 4, 4, 0, 4, 4, 0, 4, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4,
       0, 4, 0, 4, 0, 4, 0, 0, 4, 0, 0, 4, 0, 4, 0, 4, 4, 4, 0, 0, 0, 4,
       0, 4, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 0,
       0, 0, 0, 0, 0, 0, 4, 4, 0, 4, 0, 4, 4, 4, 0, 0, 0, 4, 0, 4, 0, 0,
       4, 0, 4, 0, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 0, 4,
       0, 4, 4, 0, 4, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 4, 0, 0, 4, 0, 4, 4,
       4, 4, 4, 4, 0, 0, 4, 0, 0, 4, 4, 4, 0, 0, 4, 0, 0, 0, 0, 0, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 0, 0, 0, 4, 4, 4, 4, 4, 4,
       0, 4, 4, 0, 4, 4, 4, 4, 4, 0, 4, 0, 0, 4, 0, 0, 4, 4, 0, 4, 0, 0,
       0, 0, 0, 4, 4, 4, 4, 0, 4, 0, 4, 0, 0, 0, 4, 4, 0, 4, 4, 4, 0, 0,
       0, 4, 4, 4, 4, 4, 4, 0, 0, 4, 0, 4, 0, 4, 0,

In [ ]:
data_preprocessed['Excessive Absenteeism'] =targets

In [ ]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      4  
1                      0  
2                      0  
3                      4  
4                      0

#A comment on the  target

In [ ]:
targets.sum()/targets.shape[0]


1.822857142857143

In [ ]:
data_with_targets =data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

In [ ]:
data_with_targets is data_preprocessed

False

In [ ]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      4  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      4  
4               30          0         2     1                      0

#select inputs for regression


In [ ]:
data_with_targets.shape

(700, 15)

In [ ]:
data_with_targets.iloc[:,:14]


Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [ ]:
data_with_targets.iloc[:, :-1]


Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [ ]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

standardize the data

In [ ]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()


In [ ]:
#unscaled_inputs = data_with_targets.values


In [ ]:
#absenteeism_scaler.fit(unscaled_inputs)


In [ ]:

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [ ]:
#scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [ ]:

scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.88046927,
         0.26848661,  1.09286658],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.01928035,
        -0.58968976, -0.91502478],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.91902997,
        -0.58968976, -0.91502478],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.91902997,
        -0.58968976,  1.09286658],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.91902997,
        -0.58968976, -0.91502478],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.01928035,
         0.26848661, -0.91502478]])

In [ ]:
scaled_inputs.shape

(700, 15)

## Split the data into train & test and shuffle


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)


In [ ]:
print (x_train.shape, y_train.shape)


(560, 15) (560,)


In [ ]:
print (x_test.shape, y_test.shape)

(140, 15) (140,)


#logistic regression with sklearn

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
from sklearn import metrics

tarining the model

In [ ]:
reg = LogisticRegression()

In [ ]:
# assess the train accuracy of the model
reg.fit(x_train,y_train)

LogisticRegression()

In [ ]:
# assess the train accuracy of the model
reg.score(x_train,y_train)

1.0

In [ ]:
#manual testing
model_outputs = reg.predict(x_train)
model_outputs

array([0, 4, 4, 4, 4, 0, 0, 4, 0, 4, 0, 4, 4, 0, 0, 0, 0, 0, 4, 4, 0, 0,
       4, 4, 0, 0, 0, 0, 4, 0, 0, 4, 0, 4, 0, 0, 0, 4, 4, 4, 4, 0, 4, 4,
       4, 0, 0, 0, 4, 4, 4, 4, 0, 0, 0, 4, 4, 0, 0, 4, 0, 0, 4, 0, 0, 0,
       0, 0, 0, 4, 0, 4, 4, 0, 0, 4, 4, 0, 0, 4, 4, 0, 0, 4, 0, 4, 0, 4,
       4, 4, 0, 0, 4, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0, 4, 4, 0, 0, 4, 0,
       0, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 4, 0, 0, 0, 4, 0, 4, 0, 0, 4, 4,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 4, 4, 0, 0, 0, 4, 0, 0, 0, 4,
       0, 4, 0, 0, 0, 4, 4, 0, 4, 4, 0, 0, 4, 4, 4, 0, 0, 0, 0, 0, 4, 0,
       0, 0, 0, 0, 4, 0, 0, 4, 4, 4, 0, 4, 0, 0, 0, 4, 4, 0, 0, 0, 0, 4,
       4, 0, 0, 4, 4, 4, 0, 0, 0, 4, 0, 0, 4, 4, 4, 0, 0, 4, 0, 4, 0, 0,
       4, 0, 0, 0, 0, 0, 4, 0, 4, 0, 0, 4, 4, 4, 4, 0, 4, 4, 0, 0, 0, 0,
       0, 0, 4, 0, 4, 4, 4, 4, 4, 0, 4, 0, 4, 0, 4, 4, 4, 4, 4, 4, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 0, 4, 0, 4, 0, 0, 0, 4, 0, 0, 0,
       4, 0, 4, 0, 0, 0, 0, 4, 0, 4, 0, 0, 4, 4, 0,

In [ ]:
y_train

array([0, 4, 4, 4, 4, 0, 0, 4, 0, 4, 0, 4, 4, 0, 0, 0, 0, 0, 4, 4, 0, 0,
       4, 4, 0, 0, 0, 0, 4, 0, 0, 4, 0, 4, 0, 0, 0, 4, 4, 4, 4, 0, 4, 4,
       4, 0, 0, 0, 4, 4, 4, 4, 0, 0, 0, 4, 4, 0, 0, 4, 0, 0, 4, 0, 0, 0,
       0, 0, 0, 4, 0, 4, 4, 0, 0, 4, 4, 0, 0, 4, 4, 0, 0, 4, 0, 4, 0, 4,
       4, 4, 0, 0, 4, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0, 4, 4, 0, 0, 4, 0,
       0, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 4, 0, 0, 0, 4, 0, 4, 0, 0, 4, 4,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 4, 4, 0, 0, 0, 4, 0, 0, 0, 4,
       0, 4, 0, 0, 0, 4, 4, 0, 4, 4, 0, 0, 4, 4, 4, 0, 0, 0, 0, 0, 4, 0,
       0, 0, 0, 0, 4, 0, 0, 4, 4, 4, 0, 4, 0, 0, 0, 4, 4, 0, 0, 0, 0, 4,
       4, 0, 0, 4, 4, 4, 0, 0, 0, 4, 0, 0, 4, 4, 4, 0, 0, 4, 0, 4, 0, 0,
       4, 0, 0, 0, 0, 0, 4, 0, 4, 0, 0, 4, 4, 4, 4, 0, 4, 4, 0, 0, 0, 0,
       0, 0, 4, 0, 4, 4, 4, 4, 4, 0, 4, 0, 4, 0, 4, 4, 4, 4, 4, 4, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 0, 4, 0, 4, 0, 0, 0, 4, 0, 0, 0,
       4, 0, 4, 0, 0, 0, 0, 4, 0, 4, 0, 0, 4, 4, 0,

In [ ]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [ ]:
np.sum((model_outputs==y_train))

560

In [ ]:
model_outputs.shape[0]

560

In [ ]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

1.0

In [ ]:
reg.intercept_

array([-0.50436278])

In [ ]:
reg.coef_

array([[ 0.37456159,  0.03373396,  0.30813985, -0.00706326,  0.07679174,
        -0.03410445,  0.22981861,  0.01058031, -0.05459062, -0.00642082,
         0.08476015, -0.04710614,  0.1510807 , -0.09193314,  4.5860414 ]])

In [ ]:
feature_names = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1).columns.values


In [ ]:
# get the column names of the features used in the model
feature_names = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1).columns.values


summary_table = pd.DataFrame(columns=['Feature name'], data=feature_names)

# add the coefficient values to the summary table
summary_table['Coefficient'] = np.transpose(reg.coef_)

# display the summary table
summary_table


Feature name  Coefficient
0                  Reason_1     0.374562
1                  Reason_2     0.033734
2                  Reason_3     0.308140
3                  Reason_4    -0.007063
4               Month Value     0.076792
5           Day of the Week    -0.034104
6    Transportation Expense     0.229819
7          Distance to Work     0.010580
8                       Age    -0.054591
9   Daily Work Load Average    -0.006421
10          Body Mass Index     0.084760
11                Education    -0.047106
12                 Children     0.151081
13                     Pets    -0.091933
14    Excessive Absenteeism     4.586041

In [ ]:
# do a little Python trick to move the intercept to the top of the summary table
# move all indices by 1
summary_table.index = summary_table.index + 1

# add the intercept at index 0
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

# sort the df by index
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.504363
1                  Reason_1     0.374562
2                  Reason_2     0.033734
3                  Reason_3     0.308140
4                  Reason_4    -0.007063
5               Month Value     0.076792
6           Day of the Week    -0.034104
7    Transportation Expense     0.229819
8          Distance to Work     0.010580
9                       Age    -0.054591
10  Daily Work Load Average    -0.006421
11          Body Mass Index     0.084760
12                Education    -0.047106
13                 Children     0.151081
14                     Pets    -0.091933
15    Excessive Absenteeism     4.586041

## Interpreting the coefficients



In [ ]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [ ]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.504363    0.603890
1                  Reason_1     0.374562    1.454354
2                  Reason_2     0.033734    1.034309
3                  Reason_3     0.308140    1.360891
4                  Reason_4    -0.007063    0.992962
5               Month Value     0.076792    1.079817
6           Day of the Week    -0.034104    0.966471
7    Transportation Expense     0.229819    1.258372
8          Distance to Work     0.010580    1.010636
9                       Age    -0.054591    0.946873
10  Daily Work Load Average    -0.006421    0.993600
11          Body Mass Index     0.084760    1.088456
12                Education    -0.047106    0.953986
13                 Children     0.151081    1.163091
14                     Pets    -0.091933    0.912166
15    Excessive Absenteeism     4.586041   98.105301

In [ ]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
15    Excessive Absenteeism     4.586041   98.105301
1                  Reason_1     0.374562    1.454354
3                  Reason_3     0.308140    1.360891
7    Transportation Expense     0.229819    1.258372
13                 Children     0.151081    1.163091
11          Body Mass Index     0.084760    1.088456
5               Month Value     0.076792    1.079817
2                  Reason_2     0.033734    1.034309
8          Distance to Work     0.010580    1.010636
10  Daily Work Load Average    -0.006421    0.993600
4                  Reason_4    -0.007063    0.992962
6           Day of the Week    -0.034104    0.966471
12                Education    -0.047106    0.953986
9                       Age    -0.054591    0.946873
14                     Pets    -0.091933    0.912166
0                 Intercept    -0.504363    0.603890

#Testing the model



In [ ]:
reg.score(x_test,y_test)

1.0

In [ ]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba


array([[0.99390232, 0.00609768],
       [0.0126048 , 0.9873952 ],
       [0.00986373, 0.99013627],
       [0.99484024, 0.00515976],
       [0.00338602, 0.99661398],
       [0.00725913, 0.99274087],
       [0.00675837, 0.99324163],
       [0.00424222, 0.99575778],
       [0.99467747, 0.00532253],
       [0.01666563, 0.98333437],
       [0.00996059, 0.99003941],
       [0.00642747, 0.99357253],
       [0.00325442, 0.99674558],
       [0.01629738, 0.98370262],
       [0.00600234, 0.99399766],
       [0.01333196, 0.98666804],
       [0.99113118, 0.00886882],
       [0.01185075, 0.98814925],
       [0.00753294, 0.99246706],
       [0.00270065, 0.99729935],
       [0.9932256 , 0.0067744 ],
       [0.99472054, 0.00527946],
       [0.0082312 , 0.9917688 ],
       [0.98860165, 0.01139835],
       [0.00579638, 0.99420362],
       [0.99412944, 0.00587056],
       [0.99111589, 0.00888411],
       [0.02282242, 0.97717758],
       [0.98079967, 0.01920033],
       [0.99459808, 0.00540192],
       [0.

In [ ]:
predicted_proba.shape

(140, 2)

In [ ]:
predicted_proba[:,1]

array([0.00609768, 0.9873952 , 0.99013627, 0.00515976, 0.99661398,
       0.99274087, 0.99324163, 0.99575778, 0.00532253, 0.98333437,
       0.99003941, 0.99357253, 0.99674558, 0.98370262, 0.99399766,
       0.98666804, 0.00886882, 0.98814925, 0.99246706, 0.99729935,
       0.0067744 , 0.00527946, 0.9917688 , 0.01139835, 0.99420362,
       0.00587056, 0.00888411, 0.97717758, 0.01920033, 0.00540192,
       0.98698409, 0.99290757, 0.01346077, 0.9904524 , 0.00527946,
       0.9889954 , 0.00547852, 0.99408619, 0.98804407, 0.99110277,
       0.00549638, 0.98874565, 0.00553773, 0.01139094, 0.01818558,
       0.99192749, 0.99294883, 0.00620146, 0.00528985, 0.00486793,
       0.99157639, 0.0092464 , 0.99242817, 0.00644016, 0.99523219,
       0.00892813, 0.99627179, 0.98346337, 0.00901741, 0.00904926,
       0.99285574, 0.99235842, 0.00674658, 0.01926308, 0.98185476,
       0.00613781, 0.00509976, 0.00570056, 0.99399325, 0.98506197,
       0.00544509, 0.00878652, 0.99590903, 0.00832649, 0.99105

#save the model

In [ ]:
import pickle

In [ ]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [ ]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)